---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/comments":
    get:
      summary: list comments
      tags:
      - Comments
      description: Get comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      tags:
      - Comments
      description: Create comment
      responses:
        '200':
          description: successful
  "/api/v1/comments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      tags:
      - Comments
      description: Get comment
      responses:
        '200':
          description: successful
    patch:
      summary: update comment
      tags:
      - Comments
      description: Update comment
      responses:
        '200':
          description: successful
    put:
      summary: update comment
      tags:
      - Comments
      description: Put comment
      responses:
        '200':
          description: successful
    delete:
      summary: delete comment
      tags:
      - Comments
      description: Delete comment
      responses:
        '200':
          description: successful
  "/api/v1/desks":
    get:
      summary: list desks
      tags:
      - Desks
      description: Get desks
      responses:
        '200':
          description: successful
    post:
      summary: create desk
      tags:
      - Desks
      description: Create desk
      responses:
        '200':
          description: successful
  "/api/v1/desks/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show desk
      tags:
      - Desks
      description: Get desk by id
      responses:
        '200':
          description: successful
    patch:
      summary: update desk
      tags:
      - Desks
      description: Update desk
      responses:
        '200':
          description: successful
    put:
      summary: update desk
      tags:
      - Desks
      description: Update desk
      responses:
        '200':
          description: successful
    delete:
      summary: delete desk
      tags:
      - Desks
      description: Delete desk
      responses:
        '200':
          description: successful
  "/api/v1/projects":
    get:
      summary: list projects
      tags:
      - Projects
      description: Get projects
      responses:
        '200':
          description: successful
    post:
      summary: create project
      tags:
      - Projects
      description: Create projects
      responses:
        '200':
          description: successful
  "/api/v1/projects/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show project
      tags:
      - Projects
      description: Get project
      responses:
        '200':
          description: successful
    patch:
      summary: update project
      tags:
      - Projects
      description: Update project
      responses:
        '200':
          description: successful
    put:
      summary: update project
      tags:
      - Projects
      description: Update project
      responses:
        '200':
          description: successful
    delete:
      summary: delete project
      tags:
      - Projects
      description: Delete project
      responses:
        '200':
          description: successful
  "/api/v1/tasks/{id}/comments":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: comments task
      tags:
      - Tasks
      description: Get comments by task id
      responses:
        '200':
          description: successful
  "/api/v1/tasks":
    get:
      summary: list tasks
      tags:
      - Tasks
      description: Get tasks list
      responses:
        '200':
          description: successful
    post:
      summary: create task
      tags:
      - Tasks
      description: Create task
      responses:
        '200':
          description: successful
  "/api/v1/tasks/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show task
      tags:
      - Tasks
      description: Get task by id
      responses:
        '200':
          description: successful
    patch:
      summary: update task
      tags:
      - Tasks
      description: Update task
      responses:
        '200':
          description: successful
    put:
      summary: update task
      tags:
      - Tasks
      description: Put task
      responses:
        '200':
          description: successful
    delete:
      summary: delete task
      tags:
      - Tasks
      description: Delete task
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: Retrieves all users
      tags:
      - Users
      responses:
        '200':
          description: Users found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - last_name
                  - email
                  - created_at
                  - updated_at
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - last_name
              - email
              - password
  "/api/v1//users/{id}":
    get:
      summary: Retrieves a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  last_name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - name
                - last_name
                - email
        '404':
          description: user not found
  "/api/v1/users/{id}":
    patch:
      summary: Updates a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user updated
        '422':
          description: invalid request
        '404':
          description: user not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
    delete:
      summary: Deletes a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: user deleted
        '404':
          description: user not found
  "/api/v1/login":
    post:
      summary: Logs in a user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: logged in successfully
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/reset":
    post:
      summary: Resets a user password
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Password reset successfully
        '404':
          description: Link not valid or expired
        '422':
          description: Invalid request
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
