# frozen_string_literal: true

FRONT = [
  'Implement responsive design for a website using CSS media queries.',
  'Build a custom dropdown component using HTML, CSS, and JavaScript.',
  'Create an animated menu using CSS transitions and transforms.',
  'Use Ajax to fetch data from an API and display it on a page.',
  'Build a slider component using React or Vue.js.',
  'Create a form validation library using JavaScript.',
  'Implement accessibility best practices for a website.',
  'Build a custom modal component using React or Vue.js.',
  'Use WebSockets to create real-time updates for a chat application.',
  'Build a carousel component using React or Vue.js.',
  'Implement lazy loading for images on a website.',
  'Create a custom data visualization using D3.js or Chart.js.',
  'Build a responsive navigation bar using Bootstrap.',
  'Use Redux to manage state for a React application.',
  'Implement server-side rendering for a React application.',
  'Create an authentication system using JSON Web Tokens (JWT).',
  'Build a search component that filters data in real-time.',
  'Implement pagination for a table or list of data.',
  'Use Sass to modularize and organize CSS code.',
  'Create a mobile app using React Native.',
  'Implement internationalization for a website using i18n.',
  'Build a custom video player using HTML5 video and JavaScript.',
  'Use WebGL to create a 3D animation or game.',
  'Build a progressive web app (PWA) using Service Workers and the Web App Manifest.',
  'Create a custom PDF generator using JavaScript.'
].freeze

QA = [
  'Write test cases for new features and ensure that they are covered by automated tests.',
  'Conduct exploratory testing to find any defects or issues in the application that may not have been identified during regular testing.',
  'Participate in code reviews to ensure that code changes do not adversely affect the quality of the product.',
  'Collaborate with developers and other team members to identify and resolve issues.',
  'Conduct regression testing to ensure that changes made to the product do not introduce new defects.',
  'Work with product owners to identify requirements and ensure that they are reflected in the test cases.',
  'Monitor production systems for issues and proactively address them.',
  'Participate in daily stand-up meetings to provide updates on testing progress and raise any issues or concerns.',
  'Develop and maintain documentation related to testing processes and procedures.',
  'Assist with the implementation of automated testing tools and processes.',
  'Continuously improve testing processes and procedures to ensure that the quality of the product is maintained.',
  'Conduct load testing and performance testing to identify bottlenecks and other performance issues.',
  'Conduct security testing to identify potential vulnerabilities and ensure that the product is secure.',
  'Ensure that the application is compatible with different web browsers and mobile devices.',
  'Work with customer support to identify and resolve issues reported by customers.',
  'Collaborate with the development team to ensure that the product meets user requirements.',
  'Ensure that the product is compliant with relevant regulatory requirements.',
  'Participate in user acceptance testing to ensure that the product meets user expectations.',
  'Use defect tracking tools to track and manage issues.',
  'Continuously monitor and improve the quality of the testing process.',
  'Analyze test results and provide feedback to the development team.',
  'Conduct integration testing to ensure that different components of the application work together seamlessly.',
  'Ensure that the product meets accessibility standards.',
  'Provide training to other team members on testing processes and procedures.',
  'Stay up-to-date with the latest testing techniques and tools.'
].freeze

BACK = [
  'Build a RESTful API using Node.js and Express.',
  'Create a database schema for a new application using SQL.',
  'Use a NoSQL database like MongoDB to store data.',
  'Build a custom authentication system using Passport.js.',
  'Implement caching using Redis or Memcached.',
  'Write a custom middleware for an Express application.',
  'Use a message broker like RabbitMQ to implement message queuing.',
  'Build a custom file upload service using AWS S3.',
  'Implement pagination and sorting for a database query.',
  'Use Docker to containerize a Node.js application.',
  'Write unit tests using a testing framework like Jest or Mocha.',
  'Implement rate limiting and throttling for an API.',
  'Build a custom middleware for an authentication system.',
  'Use WebSockets to create real-time updates for a chat application.',
  'Use GraphQL to build an API that allows for flexible queries.',
  'Implement OAuth2 authentication for a web application.',
  'Create a custom middleware for logging and error handling.',
  'Implement versioning for an API using URL versioning or headers.',
  'Use TypeScript to add type checking to a Node.js application.',
  'Write integration tests using a testing framework like Supertest.',
  'Implement email sending and receiving using SMTP or IMAP.',
  'Use AWS Lambda to build serverless functions for an application.',
  'Create a custom caching layer using Redis or Memcached.',
  'Build a custom job queue using Bull or Agenda.',
  'Use a load balancer like Nginx or HAProxy to scale an application.'
].freeze

COMMENT = [
  'Excellent job!',
  'Needs improvement, try again.',
  'Great work!',
  'Not quite there yet, keep practicing.',
  'Impressive!',
  'Some minor issues to address, but overall good.',
  'Well done!',
  'Could be better, but still good effort.',
  'Outstanding!',
  'Needs some refinement, but good start.'].freeze

NAME = %w[Velma Gertrude Jennine Cherise Jesus Roselyn Leanam Ching Davis Douglas]
